project:
  name: udagram
  regions:
  - us-west-2
  parameters:
    S3BucketName: '$[taskcat_autobucket]'
    S3KeyPrefix: 'udagram/'
    LicenseToken: 'test-token'
    KeyPair: my-test-ec2-keypair
    AvailabilityZones: '$[taskcat_genaz_1]'
tests:
  rolesTest:
    template: templates/networks.yml