Parameters:
  AmazonS3ReadOnlyAccess:
    Description: 'Access role for S3'
    Type: String
    Default: 'AmazonS3ReadOnlyAccess'

Resources:
  AmazonS3ReadOnlyAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  AmazonS3ReadOnlyAccessPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AmazonS3ReadOnlyAccess}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - "s3:List*"
            - "s3:Get*"
          Resource: 
            - "arn:aws:s3:::mirza-udagram/*"
      Roles:
      - !Ref AmazonS3ReadOnlyAccessRole
  AmazonS3ReadOnlyAccessInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref AmazonS3ReadOnlyAccessRole

Outputs: 
  AmazonS3ReadOnlyAccessInstanceProfile: 
      Description: Role to access S3
      Value: !Ref AmazonS3ReadOnlyAccessInstanceProfile
      Export:
        Name: AmazonS3ReadOnlyAccessInstanceProfile